server:
  port: 8000
app:
  api-prefix: /api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: account_service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/account/**
          filters:
            - StripPrefix=2
        - id: profile_service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/profile/users/**
          filters:
            - StripPrefix=2