server:
  port: 8081
  servlet:
    context-path: /account


spring:
  application:
    name: account-service
  datasource:
    url: jdbc:mysql://localhost:3306/cinema_online
    username: ${DBMS_USERNAME:root}
    password: ${DBMS_PASSWORD:123456}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_USERNAME:vuquangtrung098765@gmail.com}
    password: ${EMAIL_PASSWORD:rmawynzbfashrovv}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

jwtSignerKey:
  access: h0W6M8VNfODz9SMSgtmzh2B63q8F4xEwyWuwcG6DMGeSYe1UA5EN3NOwIBkb7BUv
  refresh: U3fCUgmxJG/U5EwINn2nIzY5xPwNtGQKDAszzxhS3tOD4yBLHztW+Q+X3her8fwt

valid-duration: 900
refreshable-duration: 3600
timeDeleteTokenInvalid: 3000